---
backend:
  azurerm:
    resource_group_name: "rg-test"
    storage_account_name: "satfstatetest"
    location: "uksouth"
stacks:
  deploy_environment_stacks: false
  deploy_region_stacks: false
  environments:
    prd:
      tags:
        - "test_tag_prd"
    dev:
      tags:
        - "test_tag_dev"
        - "test_tag_dev2"
  regions:
    uks:
    ukw:
  resource_types:
    frontdoor:
      tags:
        - "frontdoor_tag"
      exclude_environments:
        - dev
    virtual_machines:
      tags:
        - "virtual_machines_tag"
      exclude_environments:
        - prd
